p8105\_hw1\_acm2268
================
Amanda Miles
9/29/2021

\#Question 1

\#\#Creating a Data Frame

``` r
set.seed(50)

p1_df = tibble(
  r_sample = rnorm(10),
  pos_vec = r_sample > 0,
  char_vec = c("sara", "steven", "kathryn", "diane", "doug", "anne", "vanessa", "justin", "kaitlyn", "jack"),
  fact_vec = factor(c("blonde","brunette", "brunette", "black", "brunette", "blonde", "brunette", "black", "blonde", "blonde" ))
)

p1_df
```

    ## # A tibble: 10 x 4
    ##    r_sample pos_vec char_vec fact_vec
    ##       <dbl> <lgl>   <chr>    <fct>   
    ##  1   0.550  TRUE    sara     blonde  
    ##  2  -0.842  FALSE   steven   brunette
    ##  3   0.0330 TRUE    kathryn  brunette
    ##  4   0.524  TRUE    diane    black   
    ##  5  -1.73   FALSE   doug     brunette
    ##  6  -0.278  FALSE   anne     blonde  
    ##  7   0.361  TRUE    vanessa  brunette
    ##  8  -0.591  FALSE   justin   black   
    ##  9   0.976  TRUE    kaitlyn  blonde  
    ## 10  -1.45   FALSE   jack     blonde

\#Taking the mean

``` r
r_sample_mean = mean(pull(p1_df, r_sample))
pos_vec_mean = mean(pull(p1_df, pos_vec))
char_vec_mean = mean(pull(p1_df, char_vec))
```

    ## Warning in mean.default(pull(p1_df, char_vec)): argument is not numeric or
    ## logical: returning NA

``` r
fact_vec_mean = mean(pull(p1_df, fact_vec))
```

    ## Warning in mean.default(pull(p1_df, fact_vec)): argument is not numeric or
    ## logical: returning NA

``` r
r_sample_mean
```

    ## [1] -0.2440498

``` r
pos_vec_mean
```

    ## [1] 0.5

``` r
char_vec_mean
```

    ## [1] NA

``` r
fact_vec_mean
```

    ## [1] NA

I was able to take the mean of the random sample of size 10 (r\_Sample),
which had a mean of -0.2440498. I was also able to take the mean of the
logical vector indicating whether elements of the sample are greater
than 0 (pos\_vec), which was 0.5. However, I was unable to take the mean
of the character vector or the factor vector. This makes sense since
these two variables are not numeric so we cannot take their mean.

\#Converting variables to numeric

``` r
as.numeric(pull(p1_df, r_sample))
```

    ##  [1]  0.54966989 -0.84160374  0.03299794  0.52414971 -1.72760411 -0.27786453
    ##  [7]  0.36082844 -0.59091244  0.97559055 -1.44574995

``` r
as.numeric(pull(p1_df, pos_vec))
```

    ##  [1] 1 0 1 1 0 0 1 0 1 0

``` r
as.numeric(pull(p1_df, char_vec))
```

    ## Warning: NAs introduced by coercion

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(pull(p1_df, fact_vec))
```

    ##  [1] 2 3 3 1 3 2 3 1 2 2

\#Question 2

\#\#Load dataset

``` r
data("penguins", package = "palmerpenguins")
```

\#\#Describe dataset

``` r
skimr::skim(penguins)
```

|                                                  |          |
|:-------------------------------------------------|:---------|
| Name                                             | penguins |
| Number of rows                                   | 344      |
| Number of columns                                | 8        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |          |
| Column type frequency:                           |          |
| factor                                           | 3        |
| numeric                                          | 5        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |          |
| Group variables                                  | None     |

Data summary

**Variable type: factor**

| skim\_variable | n\_missing | complete\_rate | ordered | n\_unique | top\_counts                 |
|:---------------|-----------:|---------------:|:--------|----------:|:----------------------------|
| species        |          0 |           1.00 | FALSE   |         3 | Ade: 152, Gen: 124, Chi: 68 |
| island         |          0 |           1.00 | FALSE   |         3 | Bis: 168, Dre: 124, Tor: 52 |
| sex            |         11 |           0.97 | FALSE   |         2 | mal: 168, fem: 165          |

**Variable type: numeric**

| skim\_variable      | n\_missing | complete\_rate |    mean |     sd |     p0 |     p25 |     p50 |    p75 |   p100 | hist  |
|:--------------------|-----------:|---------------:|--------:|-------:|-------:|--------:|--------:|-------:|-------:|:------|
| bill\_length\_mm    |          2 |           0.99 |   43.92 |   5.46 |   32.1 |   39.23 |   44.45 |   48.5 |   59.6 | ▃▇▇▆▁ |
| bill\_depth\_mm     |          2 |           0.99 |   17.15 |   1.97 |   13.1 |   15.60 |   17.30 |   18.7 |   21.5 | ▅▅▇▇▂ |
| flipper\_length\_mm |          2 |           0.99 |  200.92 |  14.06 |  172.0 |  190.00 |  197.00 |  213.0 |  231.0 | ▂▇▃▅▂ |
| body\_mass\_g       |          2 |           0.99 | 4201.75 | 801.95 | 2700.0 | 3550.00 | 4050.00 | 4750.0 | 6300.0 | ▃▇▆▃▂ |
| year                |          0 |           1.00 | 2008.03 |   0.82 | 2007.0 | 2007.00 | 2008.00 | 2009.0 | 2009.0 | ▇▁▇▁▇ |

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

\#\#Make scatterplot

``` r
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_acm2268_files/figure-gfm/plots-1.png)<!-- -->

``` r
ggsave("p8105_hw1_plot_acm2268.pdf", height = 3, width = 5)
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

The penguins dataset has 344 rows and 8 columns. It contains 8
variables, including penguin species, island, penguin sex, penguin bill
length in millimeters, bill depth in millimeters, flipper length in
millimeters, body mass in grams, and the year. Three of these are factor
variables (species, island, sex) and five are numeric variables
(bill\_length\_mm, bill\_depth\_mm, flipper\_length\_mm, body\_mass\_g,
year). The mean flipper length is 200.92 millimeters.
